import type { PRData } from "./types";

const thrusterPatch = [
  "@@ -12,9 +12,14 @@ export class ThrusterController {",
  "   private burnRate = 0.4;",
  "   private fuel: number;",
  " ",
  "-  ignite(throttle: number) {",
  "-    this.fuel -= this.burnRate;",
  "-    return throttle * this.burnRate;",
  "+  ignite(throttle: number, dt: number) {",
  "+    const clamped = Math.min(Math.max(throttle, 0), 1);",
  "+    const burn = this.burnRate * clamped * dt;",
  "+    if (this.fuel < burn) {",
  "+      return 0; // flame-out: not enough fuel for this tick",
  "+    }",
  "+    this.fuel -= burn;",
  "+    return burn * THRUST_PER_UNIT;",
  "   }",
  " ",
  "   refuel(amount: number) {",
  "@@ -31,6 +36,10 @@ export class ThrusterController {",
  "   get remaining() {",
  "     return this.fuel;",
  "   }",
  "+",
  "+  get isFlaming() {",
  "+    return this.fuel > 0;",
  "+  }",
  " }",
].join("\n");

const scorePatch = [
  "@@ -4,12 +4,16 @@ const SCORE_KEY = 'hi-score';",
  " export function saveHighScore(score: number) {",
  "-  localStorage.setItem(SCORE_KEY, String(score));",
  "+  const previous = loadHighScore();",
  "+  if (score > previous) {",
  "+    localStorage.setItem(SCORE_KEY, String(score));",
  "+  }",
  " }",
  " ",
  " export function loadHighScore(): number {",
  "-  return Number(localStorage.getItem(SCORE_KEY));",
  "+  const raw = localStorage.getItem(SCORE_KEY);",
  "+  const parsed = raw === null ? 0 : Number.parseInt(raw, 10);",
  "+  return Number.isFinite(parsed) ? parsed : 0;",
  " }",
].join("\n");

const hudPatch = [
  "@@ -22,7 +22,7 @@ export function renderLives(ctx: CanvasRenderingContext2D, lives: number) {",
  "   ctx.fillStyle = PHOSPHOR_GREEN;",
  "-  for (let i = 0; i <= lives; i++) {",
  "+  for (let i = 0; i < lives; i++) {",
  "     drawShip(ctx, 8 + i * 20, 4);",
  "   }",
  " }",
].join("\n");

export const DEMO_PR: PRData = {
  owner: "spacediffs",
  repo: "training-sim",
  number: 1978,
  title: "Fix fuel burn physics and high score persistence",
  body: "Training mission: the thruster burn ignored frame time, the high score could regress, and the HUD drew one life too many.",
  htmlUrl: "https://github.com/spacediffs/training-sim/pull/1978",
  state: "open",
  additions: 24,
  deletions: 8,
  changedFiles: 3,
  author: "cmdr-nova",
  baseRef: "main",
  headRef: "fix/fuel-burn",
  truncated: false,
  files: [
    {
      filename: "src/engine/thrusters.ts",
      status: "modified",
      additions: 13,
      deletions: 3,
      patch: thrusterPatch,
    },
    {
      filename: "src/persistence/score.ts",
      status: "modified",
      additions: 9,
      deletions: 2,
      patch: scorePatch,
    },
    {
      filename: "src/hud/lives.ts",
      status: "modified",
      additions: 1,
      deletions: 1,
      patch: hudPatch,
    },
  ],
};
