import type { Hunk, PRData, Review, SessionStats } from "./types";

export interface HunkReview {
  hunk: Hunk;
  review: Review | null;
}

export function buildMarkdown(
  pr: PRData,
  entries: HunkReview[],
  score: number,
  stats: SessionStats,
): string {
  const reviewed = entries.filter((e) => e.review !== null);
  const flagged = entries.filter((e) => e.review?.verdict === "flag");
  const approved = entries.filter((e) => e.review?.verdict === "approve");
  const accuracy = stats.shotsFired > 0 ? Math.round((stats.shotsHit / stats.shotsFired) * 100) : 0;

  const lines: string[] = [
    `## 👾 SpaceDiffs review — [${pr.title}](${pr.htmlUrl})`,
    "",
    `Reviewed **${reviewed.length}/${entries.length} hunks** across ${pr.changedFiles} files. ` +
      `Final score **${score.toLocaleString()}** · cannon accuracy ${accuracy}%.`,
    "",
  ];

  if (flagged.length > 0) {
    lines.push(`### 🚩 Flagged (${flagged.length})`);
    for (const { hunk, review } of flagged) {
      const location = hunkLocation(hunk);
      lines.push(`- **\`${hunk.file}\`** (${location})`);
      if (review?.comment.trim()) {
        for (const commentLine of review.comment.trim().split("\n")) {
          lines.push(`  > ${commentLine}`);
        }
      }
    }
    lines.push("");
  } else {
    lines.push("### ✅ No flags raised", "");
  }

  if (approved.length > 0) {
    const byFile = new Map<string, number>();
    for (const { hunk } of approved) {
      byFile.set(hunk.file, (byFile.get(hunk.file) ?? 0) + 1);
    }
    lines.push(
      `### Approved hunks`,
      ...[...byFile.entries()].map(
        ([file, count]) => `- \`${file}\` (${count} hunk${count > 1 ? "s" : ""})`,
      ),
      "",
    );
  }

  const unreviewed = entries.length - reviewed.length;
  if (unreviewed > 0) {
    lines.push(
      `_${unreviewed} hunk${unreviewed > 1 ? "s" : ""} not reviewed (mission aborted early)._`,
      "",
    );
  }

  lines.push(`---`, `_Generated by [SpaceDiffs](https://spacediffs.com)_`);
  return lines.join("\n");
}

export function hunkLocation(hunk: Hunk): string {
  const firstNew = hunk.lines.find((l) => l.newLine !== null)?.newLine;
  const firstOld = hunk.lines.find((l) => l.oldLine !== null)?.oldLine;
  if (firstNew !== null && firstNew !== undefined) return `line ~${firstNew}`;
  if (firstOld !== null && firstOld !== undefined) return `old line ~${firstOld}`;
  return `hunk ${hunk.indexInFile + 1}`;
}
